name: EAS Build and Submit

on:
  push:
    branches:
      - main  # ou master, dependendo do nome da sua branch principal

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
        
      - name: Install EAS CLI globally
        run: npm install -g eas-cli
          
      - name: Build app
        run: eas build --platform android --non-interactive --no-wait 